### ISSUE TITLE
Time of Code release

### ISSUE THREAD

**Issue by liujiaheng** [zhoudaquan/rethinking_bottleneck_design#1]
Thanks for your wonderful work.
I am looking forward to your released neural network architecture code.
I want to try this network on other tasks(like face recognition).
Thanks.

**Comment by techmonsterwang** [comment]
when will the author release the code?

**Comment by zhoudaquan** [comment]
> when will the author release the code?

Hi, we are waiting for the company's approval for the code release. I thought it should be within one month. Thanks for your interest on this work :).

**Comment by zhoudaquan** [comment]
> Thanks for your wonderful work.
> I am looking forward to your released neural network architecture code.
> I want to try this network on other tasks(like face recognition).
> Thanks.

Hi,

Thanks for your interest. We are waiting for the company's approval. Will release it once got approved.

Best regards,
DQ
