### ISSUE TITLE
cannot reproduce performance and flops

### ISSUE THREAD

**Issue by linlililin123456** [zhoudaquan/rethinking_bottleneck_design#6]
Hi we are interested in the work, and are reproducing the paper, but we cannot reproduce the performance and flops of main table result, could you pls provide the pretrained model instead of only table performance? @zhoudaquan @Andrew-Qibin

**Comment by zhoudaquan** [comment]
> Hi we are interested in the work, and are reproducing the paper, but we cannot reproduce the performance and flops of main table result, could you pls provide the pretrained model instead of only table performance? @zhoudaquan @Andrew-Qibin

HI, thanks for your interest. The madd stats in the paper is after removing the bn layers. You can find the pretrained model in the output folder in the repo.
